# workflows/darkpool-matcher/workflow.yaml
staging-settings:
  user-workflow:
    workflow-name: "darkpool-matcher-staging"
    # deployment-registry: "private" # Optional: default onchain registry
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: ""

production-settings:
  user-workflow:
    workflow-name: "darkpool-matcher-prod"
    # deployment-registry: "onchain:ethereum-testnet-sepolia" # Optional: default onchain registry
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: ""
